stages:
  - test

ceph:
  stage: test
  image: docker/compose:latest
  services:
    - docker:dind
  script:
    - cd ci
    - docker-compose build
    - docker-compose run wildland-fuse-ci ./ci/ci-ceph
