FROM wildland-client-base:latest

# Maintainers:
#   Michal Kluczek <michal@wildland.io>

USER root
ARG DEBIAN_FRONTEND=noninteractive
ENV WL_ENV=dev

# Run update && install as one command:
# https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#apt-get
RUN apt-get -qy update && apt-get install -y \
      python3-pip \
      python3-venv \
      git \
      pkg-config \
      libfuse-dev \
      nano \
      apache2 \
      strace \
      fish \
      procps \
      htop \
      less \
      vim \
      ranger \
      nnn \
    && apt-get autoremove -y \
    && python3 -m venv /home/user/env/ \
    && . /home/user/env/bin/activate \
    && pip install --upgrade pip \
    && pip install --no-cache-dir --no-warn-script-location -r requirements.dev.txt \
    # --no-deps is provided in order to run service in offline mode.
    # 'install_requires' such as 'pybear @ git+https://github.com/golemfoundation/pybear#egg=0.0.20200914'
    # makes pip requesting network access on startup. This is unsuitable for offline mode.
    && pip install --no-deps -q . plugins/* \
    && chown -R user:user /home/user/env/

# Entrypoint

USER user
ENTRYPOINT ["bash", "./docker/entrypoint.dev.sh"]
