#!/usr/bin/env sh

set -ex

/home/user/env/bin/pip install . plugins/*
make -f Makefile.tutorials -C Documentation tutorials
make -C Documentation/ \
    SPHINXBUILD=/home/user/env/bin/sphinx-build \
    SPHINXOPTS=-W \
    BUILDDIR="$PWD"/artifacts/docs \
    html man pseudoxml
