#!/usr/bin/env bash

set -ex

. /home/user/env/bin/activate
. ci/install-inplace

# pytest

pytest -v \
       --cov plugins/encrypted/wildland_encrypted \
       plugins/encrypted
mv /tmp/.coverage.wildland /tmp/.coverage.wildland.pytest

# Minio

curl -so /tmp/minio https://dl.min.io/server/minio/release/linux-amd64/minio
chmod +x /tmp/minio
mkdir -p /tmp/minio-data/the-bucket/

MINIO_ROOT_USER='dmr' MINIO_ROOT_PASSWORD='/.,/.,/.,' /tmp/minio server --console-address :9001 /tmp/minio-data &

WL='python3 -m coverage run -p ./wl'

# Wildland

$WL --debug --verbose user create s3-user
$WL --debug --verbose container create s3-con --path /s3
$WL --debug --verbose storage create s3 --access-key 'dmr' --secret-key '/.,/.,/.,' --container s3-con --s3-url s3://the-bucket/ --endpoint-url 'http://127.0.0.1:9000' s3-storage
$WL --debug --verbose container create decrypted --path /decrypted
$WL --debug --verbose storage create encrypted --container decrypted --engine encfs --reference-container-url wildland::/s3:
$WL --debug --verbose start --container decrypted

# Test files

time -p chronic /bin/bash -c 'echo "foo" > ~/wildland/decrypted/file'
time -p chronic /bin/bash -c 'mkdir -p ~/wildland/decrypted/subdir/'
time -p chronic /bin/bash -c 'echo "bar" > ~/wildland/decrypted/subdir/file'

# this sleep is due to bug described in #342
time sleep 2

time -p chronic /bin/bash -c '[[ $(cat ~/wildland/decrypted/file) == "foo" ]]'
time -p chronic /bin/bash -c '[[ $(cat ~/wildland/decrypted/subdir/file) == "bar" ]]'

$WL --debug --verbose stop
