#!/usr/bin/env bash

set -ex

. /home/user/env/bin/activate
. ci/install-inplace gitlab

WL='python3 -m coverage run -p ./wl'

#setup
ROOT="$HOME/wildland"
MNT_DIR_1="gitlab-mnt-1"
MNT_DIR_2="gitlab-mnt-2"

# Create and mount two GitLab containers: with and without specified project ID
$WL --debug --verbose user create gitlab-user
$WL --debug --verbose container create GitLab-p --path "/$MNT_DIR_1"
$WL --debug --verbose storage create gitlab --container GitLab-p --personal-token $PERSONAL_GITLAB_TOKEN --projectid 27483617
$WL --debug --verbose start
$WL --debug --verbose container mount --with-subcontainers GitLab-p

# List full tree
time -p chronic tree "$ROOT"

# List /wildland directory
time -p chronic ls "$ROOT"

# List contents of the project directory
time -p chronic ls "$ROOT"/projects/ci\ example\ project/

# List contents of the timeline directory for the project
time -p test -d "$ROOT"/timeline/2021/06/16

# Checking the categories permutation
time -p test -d "$ROOT"/projects/ci\ example\ project/@labels/feature/

#labels with 2 issues
time -p test -f "$ROOT"/labels/backends/issue\ 1/issue\ 1.md
time -p test -f "$ROOT"/labels/backends/issue\ 2/issue\ 2.md

#labes with a single issue
time -p test -f "$ROOT"/labels/feature/issue\ 1/issue\ 1.md
time -p test -f "$ROOT"/labels/welcome/issue\ 2/issue\ 2.md

# Read contents of files
time -p chronic grep 'issue' "$ROOT"/projects/ci\ example\ project/issue\ 2/issue\ 2.md

# Unmount the container
time -p chronic $WL --debug --verbose container unmount GitLab-p

$WL --debug --verbose container create GitLab --path "/$MNT_DIR_2"
$WL --debug --verbose storage create gitlab --container GitLab --personal-token $PERSONAL_GITLAB_TOKEN

# Mount a GitLab container (without specified project ID)
$WL --debug --verbose container mount --with-subcontainers GitLab

# List contents of the timeline directory for the project
time -p test -d "$ROOT"/timeline/2021/06/16

#labes with a single issue
time -p test -f "$ROOT"/labels/feature/issue\ 1/issue\ 1.md
time -p test -f "$ROOT"/labels/welcome/issue\ 2/issue\ 2.md

# Unmount the container
time -p chronic $WL --debug --verbose container unmount GitLab

# Test storage template creation
$WL --debug --verbose template create gitlab --personal-token $PERSONAL_GITLAB_TOKEN --projectid 27483617 mygitlab
$WL --debug --verbose container create gitlab-template --template mygitlab
$WL --debug --verbose container mount gitlab-template

# Verify that the template creation is working
time -p chronic tree $ROOT

$WL --debug --verbose container unmount gitlab-template
